---
- name: Create document root
  file:
    path: "/var/www/{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    mode: "0755"

- name: Copy index test page
  template:
    src: "files/index.html.j2"
    dest: "/var/www/{{ item }}/index.html"

- name: Copy site virtual host
  template:
    src: "files/site.vhost.j2"
    dest: "/etc/apache2/sites-available/{{ item }}.conf"

- name: Enable site
  shell: /usr/sbin/a2ensite {{ item }}.conf